import { Resend } from 'resend';
import { env } from '../config/env.js';

export class EmailService {
  private static resendClient: Resend | null = env.RESEND_API_KEY
    ? new Resend(env.RESEND_API_KEY)
    : null;

  /**
   * Sends OTP email using Resend.
   *
   * Development:
   * - OTP can still be 123456 from OtpService
   * - Email sending is not required for local development
   *
   * Staging/Production:
   * - OTP is randomly generated by OtpService
   * - OTP is sent through Resend
   */
  static async sendOtpEmail(
    toEmail: string,
    otpCode: string
  ): Promise<boolean> {
    const normalizedEmail = toEmail.toLowerCase().trim();

    // Local development does not require actual email delivery.
    if (env.NODE_ENV === 'development') {
      console.log(
        `[EMAIL SERVICE] 🛠️ Development mode - OTP for ${normalizedEmail}: ${otpCode}`
      );

      return true;
    }

    // Resend is required outside development.
    if (!env.RESEND_API_KEY || !this.resendClient) {
      console.error(
        '[EMAIL SERVICE] ❌ RESEND_API_KEY is not configured.'
      );

      return false;
    }

    const fromAddress =
      env.EMAIL_FROM || 'LetGetIn <onboarding@letgetin.com>';

    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your Verification Code</title>
</head>

<body style="
  margin: 0;
  padding: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto,
  Helvetica, Arial, sans-serif;
  background-color: #f8fafc;
  color: #1e293b;
">

<table
  role="presentation"
  width="100%"
  cellspacing="0"
  cellpadding="0"
  border="0"
  style="background-color: #f8fafc; padding: 40px 15px;"
>
  <tr>
    <td align="center">

      <table
        role="presentation"
        width="100%"
        cellspacing="0"
        cellpadding="0"
        border="0"
        style="
          max-width: 540px;
          background-color: #ffffff;
          border-radius: 20px;
          border: 1px solid #e2e8f0;
          box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.05);
          overflow: hidden;
        "
      >

        <!-- Header -->
        <tr>
          <td style="
            background: linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%);
            padding: 32px 30px;
            text-align: center;
          ">
            <h1 style="
              margin: 0;
              color: #ffffff;
              font-size: 24px;
              font-weight: 800;
              letter-spacing: -0.5px;
            ">
              LetGetIn
            </h1>

            <p style="
              margin: 6px 0 0 0;
              color: rgba(255, 255, 255, 0.85);
              font-size: 13px;
              font-weight: 500;
            ">
              Next-Gen AI Career & Recruitment Platform
            </p>
          </td>
        </tr>

        <!-- Main content -->
        <tr>
          <td style="padding: 36px 32px 28px 32px;">

            <h2 style="
              margin: 0 0 12px 0;
              color: #0f172a;
              font-size: 18px;
              font-weight: 700;
            ">
              Account Verification
            </h2>

            <p style="
              margin: 0 0 24px 0;
              color: #475569;
              font-size: 14px;
              line-height: 1.6;
            ">
              Use the following 6-digit verification code to complete
              your sign-in or registration request.
            </p>

            <!-- OTP -->
            <table
              role="presentation"
              width="100%"
              cellspacing="0"
              cellpadding="0"
              border="0"
              style="margin: 0 0 24px 0;"
            >
              <tr>
                <td align="center" style="
                  background: #f1f5f9;
                  border-radius: 14px;
                  border: 2px dashed #cbd5e1;
                  padding: 20px;
                ">

                  <div style="
                    font-family: 'SF Mono', Consolas, Menlo, Monaco, monospace;
                    font-size: 34px;
                    font-weight: 800;
                    letter-spacing: 8px;
                    color: #4f46e5;
                  ">
                    ${otpCode}
                  </div>

                </td>
              </tr>
            </table>

            <!-- Security -->
            <table
              role="presentation"
              width="100%"
              cellspacing="0"
              cellpadding="0"
              border="0"
            >
              <tr>
                <td style="
                  background-color: #fffbeb;
                  border-radius: 12px;
                  border: 1px solid #fef3c7;
                  padding: 14px 16px;
                ">

                  <p style="
                    margin: 0;
                    color: #92400e;
                    font-size: 12px;
                    font-weight: 600;
                    line-height: 1.5;
                  ">
                    ⏱️ <strong>Expires in 5 minutes:</strong>
                    This one-time code is valid only for 5 minutes.
                  </p>

                  <p style="
                    margin: 6px 0 0 0;
                    color: #b45309;
                    font-size: 11.5px;
                    line-height: 1.5;
                  ">
                    🛡️ <strong>Security Tip:</strong>
                    Never share this code with anyone.
                    LetGetIn representatives will never ask for your
                    verification code.
                  </p>

                </td>
              </tr>
            </table>

            <p style="
              margin: 24px 0 0 0;
              color: #94a3b8;
              font-size: 12px;
              line-height: 1.5;
            ">
              If you did not request this verification code,
              you can safely ignore this email.
            </p>

          </td>
        </tr>

        <!-- Footer -->
        <tr>
          <td style="
            background-color: #f8fafc;
            padding: 20px 30px;
            text-align: center;
            border-top: 1px solid #e2e8f0;
          ">

            <p style="
              margin: 0;
              color: #94a3b8;
              font-size: 11px;
            ">
              &copy; ${new Date().getFullYear()}
              LetGetIn AI Inc. All rights reserved.
            </p>

          </td>
        </tr>

      </table>

    </td>
  </tr>
</table>

</body>
</html>
`;

    const textContent = `
Your LetGetIn Verification Code is: ${otpCode}

This code will expire in 5 minutes.

If you did not request this code, please ignore this email.
`;

    try {
      const response = await this.resendClient.emails.send({
        from: fromAddress,
        to: [normalizedEmail],
        subject: `${otpCode} is your LetGetIn verification code`,
        text: textContent,
        html: htmlContent,
      });

      if (response.error) {
        console.error(
          '[EMAIL SERVICE] ❌ Resend API error:',
          response.error
        );

        return false;
      }

      console.log(
        `[EMAIL SERVICE] ✅ Resend OTP email sent successfully to ${normalizedEmail}`
      );

      return true;
    } catch (error: unknown) {
      const message =
        error instanceof Error ? error.message : String(error);

      console.error(
        `[EMAIL SERVICE] ❌ Resend delivery failed to ${normalizedEmail}:`,
        message
      );

      return false;
    }
  }
}